spring:
    # datasource:
    #     url: jdbc:mysql://localhost:3306/spring_db?useTimezone=true&serverTimezone=UTC
    #     username: springuser
    #     password: 1234
    #     driver-class-name: com.mysql.cj.jdbc.Driver

    datasource:
        url: URL
        username: SPRING_DATASOURCE_USERNAME
        password: SPRING_DATASOURCE_PASSWORD
        driver-class-name: org.postgresql.Driver

    resources:
        cache:
            cachecontrol:
                cache-private: true
                max-age: 600